version: '3.3'

services:

  api:
    container_name: api
    build:
      context: .
      dockerfile: Dockerfile
    restart: on-failure
    volumes:
      - .:/go/src/api
    ports:
      - "3001:3001"
    links:
      - db
    depends_on:
      - db

  db:
    image: mysql:latest
    container_name: db
    restart: always
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: pass123
      MYSQL_DATABASE: blog
      MYSQL_ROOT_PASSWORD: pass123
    ports:
      - "3306:3306"
    volumes:
      - test-db:/var/lib/data

volumes:
  test-db:

networks:
  main: